name: saha
version: '0.2.1'
synopsis: A simple server for static websites with cool URIs
category: Web
author: XT
copyright: Copyright (C) 2015-2021 XT
license: AGPL-3
extra-source-files:
- README.md
- CHANGELOG.md
default-extensions:
- OverloadedStrings
- LambdaCase

ghc-options:
- -O2
- -Wall
- -rtsopts
- -static
- -threaded
- -optl-static

library:
  dependencies:

  - attoparsec
  - base
  - bytestring
  - cmark
  - cmdargs
  - directory
  - filepath
  - http-date
  - http-types
  - network
  - rawfilepath
  - text
  - time
  - unix
  - wai
  - warp

  source-dirs: library

executables:
  saha:
    dependencies:
    - base
    - saha
    main: Main.hs
    source-dirs: executable/saha
  saha-server:
    dependencies:
    - base
    - saha
    main: Main.hs
    source-dirs: executable/saha-server
